detect_objects:
  fields:
    filenames:
      required: true
      selector:
        text:
          multiple: true
    modes:
      required: false
      selector:
        select:
          multiple: true
          options:
            - multiobject
            - car_number
            - object
            - object2
            - scene
            - pedestrian
            - selfie
