detect_objects:
  target:
    entity:
      domain: camera
  fields:
    modes:
      required: false
      selector:
        select:
          multiple: true
          options:
            - multiobject
            - car_number
            - object
            - object2
            - scene
            - pedestrian
            - selfie
    file_out:
      required: false
      example: "/config/www/camera_latest.jpg"
      selector:
        template:
