detect_objects:
  target:
    entity:
      domain: camera
  fields:
    modes:
      default: ["multiobject"]
      required: false
      selector:
        select:
          multiple: true
          options:
            - multiobject
            - car_number
            - object
            - object2
            - scene
            - pedestrian
            - selfie
          translation_key: modes
    file_out:
      required: false
      example: "/config/www/vision_snapshot.jpg"
      selector:
        template:
    # config_entry_id:
    #   required: true
    #   selector:
    #     config_entry:
    #       integration: vkcloud_vision
recognize_text:
  target:
    entity:
      domain: camera
  fields:
    detailed:
      default: false
      required: false
      selector:
        boolean:
