detect_objects:
  target:
    entity:
      domain: camera
  fields:
    modes:
      default: ["multiobject"]
      required: false
      selector:
        select:
          multiple: true
          options:
            - multiobject
            - car_number
            - object
            - object2
            - scene
            - pedestrian
            - selfie
          translation_key: modes
    prob_threshold:
      default: 0.1
      required: false
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider
    file_out:
      required: false
      example: "/config/www/vision_snapshot.jpg"
      selector:
        template:
    bounding_boxes:
      default: rus
      required: false
      selector:
        select:
          options:
            - none
            - no_labels
            - rus
            - eng
          translation_key: bounding_boxes
    num_snapshots:
      default: 1
      required: false
      selector:
        number:
          min: 1
          max: 100
          mode: box
    snapshot_interval_sec:
      default: .5
      required: false
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: seconds
          mode: slider
    max_retries:
      default: 5
      required: false
      selector:
        number:
          min: 1
          max: 10
          mode: box
    # config_entry_id:
    #   required: true
    #   selector:
    #     config_entry:
    #       integration: vkcloud_vision
recognize_text:
  target:
    entity:
      domain: camera
  fields:
    detailed:
      default: false
      required: false
      selector:
        boolean:
